### ISSUE TITLE
并没有运动检测开关

### ISSUE THREAD

**Issue by goto100** [c1pher-cn/homeassistan-ezviz#1]
我发现代码里并没有实现运动检测的开关，遇到什么问题了吗？

**Comment by c1pher-cn** [comment]
没做这个，我自己的出发点只是想拿图像，动作检测没想清楚怎么做

**Comment by goto100** [comment]
ezviz 可以通过 ffmpeg 直接拿到视频啊

**Comment by c1pher-cn** [comment]
ffmpeg 对设备性能有要求，有时很卡，ha里我觉得也不需要实时性那么高，几十秒刷新一次我觉得足够了。

**Comment by xylake** [comment]
感谢您的插件。运动检测的开关在萤石摄像头app可以设置。能不能在插件里也提供运动检查的开关，这样用户自己可以在HA写自动化，决定在家时关闭运动检测，不再发送报警消息？

**Comment by goto100** [comment]
@xylake 你可以参考我这个：https://github.com/goto100/my-homeassistant-config/blob/1205/custom_components/camera/ezviz.py

**Comment by c1pher-cn** [comment]
@xylake 可以的，刚看了 @goto100 的代码，原来ha里摄像头的运动检测这么简单就可以。周末我搞搞

**Comment by xylake** [comment]
@goto100 @c1pher-cn 前人栽树，后人乘凉，多谢两位，等c1pher的测试

**Comment by c1pher-cn** [comment]
已添加运动检测开关

**Comment by kingtao1024** [comment]
> 已添加运动检测开关

您好，我安装之后为什么没有看到运动检测开关呢……只有一个Camera实体，显示画面

**Comment by c1pher-cn** [comment]
Ha升级版本后有bug我给注释掉了，最近比较忙暂时没加回去
