### ISSUE TITLE
appKey and appSecret

### ISSUE THREAD

**Issue by frederikme** [c1pher-cn/homeassistan-ezviz#2]
Where can I find or apply for the appKey and secretKey?

**Comment by frederikme** [comment]
Nevermind, you have to retrieve them by sending an email to ezviz and requesting them.

**Comment by c1pher-cn** [comment]
here it is. login first 
and then get your deviceid here https://open.ys7.com/console/device.html
get your appkey,appsecret  after create your app : https://open.ys7.com/console/application.html
